### ISSUE TITLE
climate versus carbon

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector-SA-npar#14]
Can we hold climate sensitivity and diffusion close to default Hector values and see what parameter combinations of beta and Q10 are left?

**Comment by kdorheim** [comment]
Do more Hector runs or subset current results for close to default?

**Comment by cahartin** [comment]
subset current results, with some plus/minus on the side of default values.

**Comment by kdorheim** [comment]
what should the magnitude of the plus/minus be ?
5% of the default value?

**Comment by cahartin** [comment]
i'm not sure. we can try 5% as a start.

**Comment by kdorheim** [comment]
I increased the percent range to 10% because the 5% range was too small, on 2 runs passed for most filters. 
![image](https://user-images.githubusercontent.com/27299759/42471147-ad60cdfe-838a-11e8-8a18-fbce37dc1380.png)
![image](https://user-images.githubusercontent.com/27299759/42471165-bd2648b8-838a-11e8-97e5-ad51c3e1cdc4.png)
I am not sure if the number of Hector runs is large enough to be sub setting results like this.

**Comment by kdorheim** [comment]
We decided that a 10% +/- range was too small. @cahartin wanted a percent change that spanned 2.5 to 3.5 for S, which corresponds to a 16.66666666667% change. 

I rounded up to 17% so the following plots looks at the parameter space for default S and diff with a +/- 17% change. 
![image](https://user-images.githubusercontent.com/27299759/42648568-5377a824-85d5-11e8-9972-ccf287895f66.png)
![image](https://user-images.githubusercontent.com/27299759/42648601-69c91ee6-85d5-11e8-93f8-501d6167789b.png)
![image](https://user-images.githubusercontent.com/27299759/42648632-7bdd350e-85d5-11e8-8724-6dbbbe782cf3.png)
