### ISSUE TITLE
MODIS NPP

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector-SA-npar#5]
/people/chen671/forCary/ MODIS_NPP_2000_2013.csv
longitude | latitude | 2000 | to 2013
we need to construct a globally weighted average
can we also get a std from this?

**Comment by kdorheim** [comment]
@cahartin What are the units on this? Hector values are coming in around 58 but the weighted average is closer to 400.  Is this a units inconsistency or related to the weighting method?

**Comment by cahartin** [comment]
Hector's output of NPP is in PgC/yr.   I'm not connected to PIC, are there units in Min's file?

**Comment by kdorheim** [comment]
Nope the files looks like.... 

-179.975 | 71.475 | 95.5 | 115.3 | 140.2 | 126.2 | 136.6 | 130.2 | 128.3 | 223 | 129.6 | 129 | 113.3 | 155.9 | 125.2 | 153.5
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
-179.975 | 71.425 | 59.8 | 92.6 | 94 | 95.8 | 104.3 | 104.8 | 92.8 | 184.8 | 103.6 | 108.9 | 89.4 | 126.8 | 99 | 132.1
-179.975 | 71.375 | 75.9 | 107.2 | 109.4 | 113.1 | 118.8 | 115.8 | 106.3 | 207.9 | 109.4 | 119.6 | 87.9 | 129.5 | 97.1 | 134.3
-179.975 | 71.325 | 74.9 | 108.4 | 121.2 | 118.5 | 128.3 | 118.2 | 113.4 | 200.3 | 107.1 | 122 | 89 | 132.6 | 102.2 | 138.4
-179.975 | 71.275 | 71.6 | 106.5 | 125.7 | 116.8 | 120.7 | 128 | 113.7 | 187.7 | 111.1 | 124.6 | 87.4 | 124.9 | 93.9 | 131.8

**Comment by kdorheim** [comment]
From Min 
/people/chen671/forKalyn/MODIS_NPP_2000_2013_area.csv
The last column is the grid area in km2

The unit for NPP is g C m-2 year-1.

**Comment by kdorheim** [comment]
#### MODIS Processing Summary
`hector-SA-npar/code/part_1/D.NPP_Dmetric_preprocessing.R `
* cell area units were converted from km2 to m2 to be compatible with the NPP units of g C / m2 yr
* NPP values x cell area to get the total g C / year in each cell 
* aggregate total cell NPP --> global NPP 
* convert from g C to Pg C for comparison with Hector NPP 


#### Dn metric 

* I assumed the first was that the variability use to observational error is equal to 10 % of the observation value. 
* Because there are only 13 years of observational data I did not used the rolling sd method to calculate the observational variability. Instead the gamma distribution uses a sigma value that is equal to 2 * sd of the entire observational time series.  

#### Dn results
* `1027` runs have a Dn score that "matches" observations
* `7` runs have passing Dn scores for Tgva, NPP, atm CO2, and Land Flux
